version: "3.7"
services:
  service_1:
    image: thomashennessy/app:mission
    ports:
    - target: 5000
    deploy:
      replicas: 3
  service_2:
    image: thomashennessy/dossiernumgen:mission
    ports:
    - target: 5001
    deploy:
      replicas: 3
  service_3:
    image: thomashennessy/dossierchargen:mission
    ports:
    - target: 5002
    deploy:
      replicas: 3
  service_4:
    image: thomashennessy/missiongen:mission
    ports:
    - target: 5003
    deploy:
      replicas: 4
  nginx:
    image: nginx:latest
    ports:
    - published: 80
      target: 80
    depends_on:
    - service_1
      service_2
      service_3
      service_4
  database:

